# Site Settings
title: 						"crazybit's Blog"
description: 				"Join me as I explore blockchain technology to secure life, liberty, and property for all."
baseurl: 					""
#url: 						""
logourl: 					"/assets/img/logo.png"		
fa-logo: 					"fa-bold"
paginate: 				10	


# Author Settings
author_name: 				"crazybit"
#author_url: 				"http://bitshares.org"
author_bio: 				"My name is crazybit, i am a blockchain engineer. this blog is created to share my exploring of the blockchain technology."
author_image: 			"/assets/img/logo.png"


# Social Settings
#twitter_url: 				"http://twitter.com"
#facebook_url: 				"http://facebook.com"
github_url:  				"http://github.com/crazybits"
#youtube_url:  				"http://youtube.com"
#dribbble_url:  				"http://dribbble.com"
#googleplus_url: 			"http://google.com/plus"
#instagram_url:  			"http://instagram.com"
#pinterest_url:  			"http://pinterest.com"
#linkedin_url:  				"http://linkedin.com"


# Theme Settings
theme_disqus_shortname: 	"crazybit"
theme_google_comments: 		false
theme_analytics_id: 		"UA-28282324-1"
theme_analytics_domain: 	"ecko.me"
theme_reading_time: 		true
theme_autoload_comments: 	false
theme_always_show_nav: 		true

gems:
 # - jekyll-redirect-from
  - jekyll-paginate


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown: 					kramdown
permalink: 					pretty

